supply_chain_control_tower:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "ewefaqm-lr31508"
      user: "ADITYA253032"
      private_key_path: "/Users/aditya954/.dbt/snowflake_keys/rsa_key.p8"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"
      role: "TRANSFORMER"
      database: "ANALYTICS"
      warehouse: "DBT_WH"
      schema: "STAGING"
      threads: 8
      client_session_keep_alive: false

    prod:
      type: snowflake
      account: "ewefaqm-lr31508"
      user: "ADITYA253032"
      private_key_path: "/Users/aditya954/.dbt/snowflake_keys/rsa_key.p8"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"
      role: "TRANSFORMER"
      database: "ANALYTICS"
      warehouse: "DBT_WH"
      schema: "STAGING"
      threads: 16
      client_session_keep_alive: false
